// <auto-generated />
using System;
using GuillermoAlvarez_Examen1P.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuillermoAlvarez_Examen1P.Migrations
{
    [DbContext(typeof(GuillermoAlvarez_Examen1PContext))]
    [Migration("20231025124143_GuillermoAlvarez_DB")]
    partial class GuillermoAlvarez_DB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GuillermoAlvarez_Examen1P.Models.GuillermoAlvarez_Tabla", b =>
                {
                    b.Property<int>("GA_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GA_Id"), 1L, 1);

                    b.Property<bool>("GA_ClieneInternet")
                        .HasColumnType("bit");

                    b.Property<bool>("GA_ClienteTelevisor")
                        .HasColumnType("bit");

                    b.Property<DateTime>("GA_Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("GA_Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GA_Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("GA_Id");

                    b.ToTable("GuillermoAlvarez_Tabla");
                });
#pragma warning restore 612, 618
        }
    }
}
